server/datasets/tcga/ingest.py

Also, store DiseaseStudy metadata as uppercase. This matches the tables published by TCGA.

Fix a bug in ingest, handling an undocumented disease type, "pan_lung"

---

plugin_tests/tcga_test.py
server/rest/tcga.py

@scimk I think this provides the search by keyword you wanted.

Add the ability to search metadata by a substring

---

plugin_tests/rest_test.py
server/rest/system.py

This lets you set multiple resources at a time (items or folders).  An update is done to the metadata and can involved nested keys.  For instance, `{"keya": "valuea", "keyb.keyd": "valued", "keyb.keyc": null}` will set `keya` and add or modify `keyb`.  Depending on the `allowNull` flag, the `keyc` subkey will either be removed or set to `null`.

Add a resource/metadata endpoint.

---

.travis.yml
server/__init__.py
server/rest/system.py

This also removes some duplicated code.

Include virtual folder items in recursive resource/{id}/items.

---

README.rst
docker-compose/.dockerignore
docker-compose/Dockerfile
docker-compose/README.rst
docker-compose/assetstore/.gitignore
docker-compose/db/.gitignore
docker-compose/docker-compose.yml
docker-compose/girder.local.conf
docker-compose/girder_config.py
docker-compose/logs/.gitignore
docker-compose/worker.local.cfg

This adds a close to minimal docker-compose example

Add a docker-compose example.

---

.circleci/config.yml
.gitignore
ansible/.dockerignore
ansible/Dockerfile-girder
ansible/Dockerfile-worker
ansible/deploy_docker.py
ansible/docker_ansible.yml
ansible/roles/girder/tasks/main.yml
ansible/roles/provision/tasks/main.yml
ansible/roles/worker/tasks/main.yml

This also published the docker images.

Parallelize circle-ci testings.

---

ansible/roles/girder/tasks/main.yml

Use the --pre flag when installing girder plugins.

Add archive-access plugin.

---

.circleci/config.yml
.circleci/proxy.cfg
.circleci/proxy.nginx

Test that static assets and api are accessed in the expected locations for a proxy configuration.

Test that we can use a custom config file and a proxy.

---

ansible/Dockerfile-worker

An error message was being logged on startup that didn't affect anything.  This fixes that.

Clean up the worker Dockerfile.

---

ansible/roles/provision/tasks/main.yml

This resolves #70 by supporting the old path as well.

Change webroot.

---

ansible/Dockerfile-girder
devops/deploy.sh

The devops script and Dockerfile now support working with a bind mounted local copy of girder.

Make it easier to develop with a girder repo.

---

docs/_includes/callouts.html
docs/_includes/head.html
docs/_includes/header.html
docs/_includes/hero.html
docs/_includes/menubar.html
docs/_includes/showcase.html
docs/_includes/tabs.html

This PR is a test to see if removing the baseurl prepends will fix our linking issues.

Remove baseurl prepends

---

.circleci/config.yml
docs/Gemfile.lock
docs/_config.yml
docs/_data/navigation.yml
docs/_includes/demos-examples-list.html
docs/_includes/head.html
docs/_includes/header.html
docs/_includes/hero.html
docs/_includes/subscribe.html
docs/_layouts/default.html
docs/_layouts/homepage.html
docs/_success_stories/developing-machine-learning-tools-through-collaborative-annotation-studies.md
docs/_success_stories/the-digital-slide-archive-and-tcga.md
docs/demos-examples/index.md
docs/papers-publication/index.md
docs/success-stories/index.html

We'll need to potentially put this live to see if it works or not, but thought maybe we could test it out on the circleci artifiact. If not I recommend merging. Do you agree @manthey ?

Add potential fix for broken navigation links

---

docs/_success_stories/developing-machine-learning-tools-through-collaborative-annotation-studies.md
docs/demos-examples/index.md
docs/index.md

Update Youtube link and demo.kitware.com link.

---

docs/_success_stories/developing-machine-learning-tools-through-collaborative-annotation-studies.md
docs/_success_stories/the-digital-slide-archive-and-tcga.md
docs/success-stories/index.html

This also converts some absolute references into relative references.

This fixes some remaining double slash links.

---

.circleci/config.yml
ansible/Dockerfile-girder
ansible/deploy_docker.py

Both of those are end-of-life.

Drop support for Python 2.7 and 3.5.

---

ansible/Dockerfile-girder
ansible/Dockerfile-worker

The current configuration doesn't work with ansible 4.  For now, just pin ansible.

Pin ansible.

---

devops/dsa/provision.py
devops/minimal/provision.py

This allows it to have extra settings, non-default admin, and any assetstore.

Add more options to the provisioning script.

---

.gitignore
devops/dsa/docker-compose.yml

Allow passing worker concurrency via an environment variable.

Make it easier to set worker concurrency.

---

devops/dsa/README.rst
devops/dsa/docker-compose.yml

Oddly, the previous code worked fine in ubuntu bases but not on a fresh CentOS install.  This works on both.

Improve how groups are set.

---

Dockerfile
devops/dsa/docker-compose.yml
devops/dsa/provision.py
devops/dsa/provision.yaml
devops/dsa/start_girder.sh
devops/dsa/start_worker.sh

Refactor the docker-compose script so commands are run from shell scripts.
This makes it easier to use in derivative projects.

Add provision options to create resources.

---

devops/dsa/README.rst

Prerequsities => Prerequisites

Correct README typo

---

devops/dsa/provision.py
devops/minimal/provision.py

This removes a manual step when upgrading mongo versions.

When provisioning, set the mongo feature compatibility version.

---

Vagrantfile
devops/dsa/provision.py
devops/dsa/start_girder.sh
devops/dsa/start_worker.sh
devops/dsa/utils/cli_test.py

Use docker-compose for Vagrantfile.
Ensure correct permissions in worker temp file.
Add options to the cli_test program.

Improve deployment.

---

ansible/Dockerfile-girder
ansible/Dockerfile-worker

This change was caused by setuptools changes.

Fix installing pip in the dockers.

---

ansible/group_vars/all

This helps support networking inside dockers.

Switch girder-worker branch.

---

Dockerfile
ansible/group_vars/all

Switch back to master, now that the nvidia support branch is merged.

Update girder_worker branch.

---

ansible/Dockerfile-girder
ansible/roles/common/tasks/main.yml
ansible/roles/girder/tasks/main.yml

It has a bug (see github.com/pypa/setuptools/issues/3063).

Avoid setuptools 60.6.0

---

ansible/roles/girder/tasks/main.yml
ansible/roles/worker/tasks/main.yml
devops/minimal/README.rst

It now prefers https:// to git://
Also, improve minimal example readme.

Change ansible git repo references.

---

Dockerfile
ansible/roles/girder/tasks/main.yml

The import tracker will have more development, but it is a good start.

Add the import-tracker plugin

---

devops/minimal/Dockerfile

We need to install git to install things properly.

Update the minimal docker example.

---

devops/singularity-minimal/.gitignore
devops/singularity-minimal/README.rst
devops/singularity-minimal/girder.cfg

This was a rough example.  It isn't tested sufficiently, but may help enough that it is worth merging in.  Closes #167.

Singularity example.

---

devops/dsa/README.rst

Fixed typo in README

---

.circleci/config.yml

This ensures that some of the devops examples at least start.  It'd be good to test more functionality in the future.

Minimally test additional devops examples

---

devops/dsa/docker-compose.yml
devops/external-worker/docker-compose.yml
devops/minimal/docker-compose.yml
devops/singularity-minimal/README.rst

Remove the nojournal option we passed to mongo

---

devops/dsa/provision.py
devops/dsa/provision.yaml
devops/minimal/provision.py

Recently someone had an old provisioning file and it was hard to debug.

Add more logging during startup.

---

.circleci/config.yml

The linting test env name changed.

Update HistomicsUI testing.

---

devops/dsa/docker-compose.yml
devops/dsa/provision.py
devops/dsa/provision.yaml

This may become the default once some notable users verify it will work for them.

Show how to use httponly cookies

---

.gitignore
devops/dsa/provision.py
devops/singularity-minimal/singularity-compose.yml

Check in a file that was missing

When a bash or pip command fails, better report it

---

.circleci/config.yml
README.rst
ansible/migration.rst
devops/dsa/README.rst
devops/external-worker/README.rst
devops/minimal/README.rst
devops/with-dive-volview/README.rst

docker-compose is now old enough it isn't the standard.

Change docs to "docker compose" rather than "docker-compose"

---

.circleci/config.yml

Don't publish new docker containers unless all docker compose tests pass.

Ensure all docker compose tests pass before publishing docker container

---

Dockerfile

Remove `__pycache__` directories.

Reduce the common docker image size

---

devops/dsa/docker-compose.yml
devops/external-worker/docker-compose.yml
devops/minimal/docker-compose.yml
devops/with-dive-volview/docker-compose.override.yml
docs/migration.rst

Docker complains this is obsolete.

Remove docker compose version number.

---

Dockerfile

Strip some libraries.  Default to a non-dev client build.

Make the docker image smaller.

---

devops/ver5/provision.py
devops/ver5/provision.yaml
devops/ver5/start_girder.sh

In bash, "commandA && commandB & commandC", commandC will start immediately because the && creates a single group of (commandA && commandB).  Use ; before starting a background task.

Harden the version 5 start
