- plugin_tests/tcga_test.py
- server/rest/tcga.py
Adds an endpoint as follows: `/api/v1/tcga/image?caseName=<case name>`.  This will return a list of images associated with the given case (patient).  This is returns the same information as the existing endpoint `/api/v1/tcga/case/<case id>/images`, but uses the label name rather than the mongo id.
> Add an endpoint to list images from a patient name

- .travis.yml
- plugin_tests/rest_test.py
- server/rest/system.py
This adds a simple `GET item/query` endpoint that takes limit, offset, sort, and query parameters.  query is a JSON-encoded mongo query performed on items.  For instance, to find all the XTK items, query could be `json.dumps({'meta.XTK': {'$exists': True}})`.  Only items the current user can read are returned.  If you use a sort that doesn't have an index in the database, the query could fail due to Mongo's in-memory sort limit.
> Add an item/query endpoint.

- server/rest/__init__.py
- server/rest/dsa.py
@dgutman This adds to the work that @manthey had done earlier.  I have added additional comments to try and explain what is going on.  I have also added a new endpoint that does the sort of querying by metadata that you are looking for.
I suspect that you will want to do far more sophisticated queries in the future.  To ease the development process, I would recommend developing these queries outside of the endpoint code first because calling and debugging the rest endpoints themselves can be cumbersome.  Once you have something working, commit these function to a different module and call the functions inside these rest endpoint.  I generally try to keep the rest methods as simple as possible.
> Add an endpoint to query items by metadata keys

- .circleci/config.yml
- devops/dsa/Dockerfile
- devops/dsa/girder_config.py
Also, fix yarn breaking packages.  Yarn rotates a key annually; this makes it so apt-get update fails.  Since we don't use yarn, just remove the apt sources for it.
> Add a test for the docker-compose file.

- .circleci/config.yml
This runs CI once a week, rebuilding the dockers and publishing them on success.  It both confirms that everything continues to work and pulls in upstream package changes without user intervention.  We can change the frequency based on development speed.
> Periodic ci

- .circleci/config.yml
Remove references to the girder-3-deployment branch now that it is merged.
> Clean up merging girder-3-deployment branch.

- .circleci/config.yml
This allows testing before merging to master.
Browsing via circle-ci artifacts shows some peculiarity (see https://550-48765002-gh.circle-artifacts.com/0/tmp/artifacts/index.html).
> Build the website and publish circle artifacts.

- ansible/roles/girder/templates/rebuild_and_restart_girder.sh.j2
- ansible/roles/girder/templates/restart_girder.sh.j2
Before, in some instances, the script would end before the restart had happened.  Now, it should wait until the restart is complete.
> Improve restart girder scripts.

- .circleci/config.yml
- .circleci/dsa_proxy.cfg
- .circleci/dsa_proxy.nginx
- .circleci/proxy.cfg
- ansible/README.rst
- ansible/roles/provision/tasks/main.yml
As part of provisioning, rebuild girder if the static_piblic_path isn't the default.
Add some documentation about reverse proxy.
> Rebuild the girder web client when a proxy.

- ansible/roles/girder/tasks/main.yml
We should replace this with a modern tool, but this provides the same functionality we had before.
> Add the xtk demo plugin.

- ansible/README.rst
This may change when we address issue #70.
> Fix the reference to the UI location for vagrant installations.

- .circleci/config.yml
This will allow downloading the tarballs and installing them locally via a command like `docker load -i dsa_girder.tar`.
> Exposed built dockers as circle-ci artifacts.

- README.rst
- devops/README.rst
The main README now mentions how to add Docker tasks.  The devops README has been updated to reflect recent changes.
> Update the README files.

- Vagrantfile
If the vagrant-disksize plugin is available, properly resize the default disk.
> Improve how vagrant makes the initial disk.

- .circleci/config.yml
- ansible/roles/girder/tasks/main.yml
- ansible/vagrant.yml
- devops/build.sh
The devops tools still do, since it is expected you want dev mode in development.
This doesn't affect the girder python mode.
> By default, don't build the website in dev mode.

- devops/build.sh
- devops/test.sh
Before, something like `test.sh -e lintclient` wouldn't work because of how parameters were escaped.
> Fix parameter escaping in devops scripts.

- devops/build.sh
- devops/test.sh
In order to preserve whitespace in parameters, this uses some arcane bash operations.  There is probably a better way to do it, but this works in various tests.
> Fix bash parameter escaping as passed to docker.

- ansible/deploy_docker.py
This stops Girder and Girder Worker more gracefully and faster.
> Use the docker run --init flag.

- .gitignore
- ansible/deploy_docker.py
- ansible/roles/common/set_environment.py
- devops/dsa/worker.local.cfg
Allow overriding rabbitmq and girder worker config files.  This allows using non-guest rabbitmq users.
> Add options for specifying config files.

- .circleci/config.yml
- devops/dsa/Dockerfile
The default machine has Python 2.  An upstream package is mislabeled for Python 2 and doesn't work properly.
> Fix docker-compose testing.

- ansible/roles/girder/templates/worker.local.cfg.j2
- ansible/roles/provision/tasks/main.yml
- ansible/roles/worker/templates/worker.local.cfg.j2
- devops/dsa/girder_config.py
We don't do anything with the celery backend, so this change makes no changes other than reducing warnings.
> Use the rpc backend to stop celery warnings.

- ansible/Dockerfile-girder
- ansible/Dockerfile-worker
Some change in debian caused the tzdata module to hang on installation.
> Fix dockerfile build.

- ansible/deploy_docker.py
- devops/dsa/docker-compose.yml
For 1024 x 1024 tiles, 4MB are often necessary.  Allow up to 8MB.
> Increase the memcached max-item-size.

- ansible/Dockerfile-girder
- ansible/Dockerfile-worker
- ansible/docker_ansible.yml
- ansible/roles/girder/tasks/main.yml
Rather than figure out what changed that broke the 18.04/3.6 dockers, update to newer versions.
> Update dockers to use Ubuntu 20.04 and Python 3.8.

- ansible/roles/girder/templates/girder.local.cfg.j2
We set the max-request-body-size in the docker-compose deployments; also set it in the deploy_docker.py deployment.
> Update a default in the deploy_docker.py config.

- devops/dsa/provision.py
Works the same as before if you provide a dict. If you provide a list of dicts, it will iterate through each one and provision the assetstores therein.
> multiple assetstore support in provision.py

- .circleci/config.yml
- devops/dsa/provision.py
- devops/minimal/Dockerfile
The minimal docker-compose example failed on importing data because it requires girder-client.
Fixes #191.
> Fix the minimal docker-compose example.

- devops/dsa/.gitignore
- devops/dsa/README.rst
- devops/dsa/docker-compose.yml
- devops/dsa/girder.cfg
- devops/dsa/provision.py
- devops/dsa/provision.yaml
- devops/dsa/start_girder.sh
- devops/dsa/utils/cli_test.py
Modify the provisioning script to make it easier to install additional pip modules.  This allows rebuilding the girder client after such installation. 
Also, install the dsarchive/histomicstk:latest cli by default.
> Support provisioning additional girder plugins.

- README.rst
- devops/dsa/README.rst
Minor changes to the main and docker-compose readmes.
Main Readme:
-  Remove duplicate reference to docker-compose instructions
Docker-compose Readme:
-  Add cd into directory to run stated commands
-  Note on which port girder instance can be accessed
> update main and docker-compose readmes

- ansible/roles/worker/tasks/main.yml
There was a requirements file in large image that wasn't used by that project but was used here.  When it was removed from large_image, it broke the ansible build.
> Fix ansible build.

- devops/with-dive-volview/provision.divevolview.yaml
Just modifying the install of dive to use the main branch.
I've set up some CI for publishing the new releases of the DIVE client as well as building my own docker images used for testing on the main branch now.
I have set my local install to this and built/tested it to make sure it is updating properly.
> Set the DIVE install to use the main branch of the repo

- .circleci/config.yml
Stop testing with Python 3.6; add 3.11.
> Change which python versions are used to verify HistomicsUI.

- .circleci/config.yml
- devops/dsa/README.rst
- devops/dsa/start_girder.sh
- devops/dsa/start_worker.sh
- devops/dsa/utils/cli_test.py
The permissions needed for /var/run/docker.sock on OSX are different than on linux.
> Improve starting on OSX.

- Dockerfile
- ansible/roles/girder/tasks/main.yml
The girder dicom viewer and archive access plugin both require a javascript library (Daikon) where the most recent version (1.2.45) has dependencies that cause conflicts with the large_image viewer.
To resolve this, either dependencies in Girder plugins need to be pinned or the library that has an issue needs another update.
> Remove the dicom viewer plugin.

- devops/minimal/Dockerfile
The python slim-container fights with the node version we install
> Update the minimal example.

- .circleci/config.yml
- .circleci/docker-compose.proxy.yml
- .circleci/dsa_proxy.cfg
We publish two sets of docker images; the old docker images that are used with the deploy_docker.py script had fairly complete tests.  This performs those same tests on the new docker image used with docker-compose.  This is a necessary step prior to deprecating the deploy_docker.py script (docker-compose does everything we want).
> Test the dsarchive/dsa_common docker build environment

- devops/dsa/provision.py
- devops/minimal/provision.py
This change improves compatibility with upgrading to newer mongo versions.
As part of our provisioning, we automatically ask mongo to upgrade the feature compatibility version.  This means that if you upgrade the DSA deployment using standard methods, it automatically upgrades your Mongo database as you go.  In theory, should one ever need to go back, you could downgrade the mongodb version manually a step at a time.  In practice, I'm not sure any deployments downgrade mongo.
As of Mongo 7, you can no longer undo upgrades to the DB.  The upgrade process requires an additional parameter because of this, so we aren't currently (2023-08-18) upgrade the feature compatibility version.  This will lead to problems on the next mongo release.
We have a flag in the provisioning (`mongo-compat`) …
> Mongo 7 upgrade

- Dockerfile
This had been the case before a recent change, and it turns out some downstream packages depend on <3.10 (specifically the dive integration).
> Set default python to 3.9

- devops/dsa/docker-compose.yml
- devops/external-worker/docker-compose.yml
With this, `docker ps` will show something like `dsarchive/dsa_common   2 hours ago   Up 2 hours (healthy)`.  The healthcheck doesn't affect how the dockers run; it functionally is a command exec-ed in the container at a specific frequency that will report if the command succeeded or failed.
> Add docker healthchecks

- ansible/Dockerfile-girder
It will be discontinued once the deprecation message is a year old nd any other maintenance is needed (no earlier than July 2024).
> Keep deprecated deployment working for now

- .circleci/config.yml
- Dockerfile
- devops/dsa/docker-compose.yml
This appears as an ENV record in the docker history.  The actual entry is DSA_VERSIONS which is a json dictionary of the versions of some of the core libraries.
> Mark the common docker with version information

- devops/dsa/provision.py
- devops/minimal/provision.py
If an image is listed in the always-pull section as well as the pull-as-needed section, it needlessly gets catalogued twice.  This prevents that.
> Remove duplicates from list of cli images to provision

- devops/dsa/provision.py
- devops/dsa/start_girder.sh
- devops/minimal/provision.py
Girder build can't run until the end of the preprovisioning step, but it doesn't stop any of the provisioning step, so the two can be done in parallel.
> Speed up provisioning when girder build is run

- devops/dsa/start_girder.sh
This ignored the setting in the environment variables or config.
> Don't override girder mode to dev

- .circleci/config.yml
- devops/ver5/assetstore/.gitignore
- devops/ver5/db/.gitignore
- devops/ver5/docker-compose.yml
- devops/ver5/logs/.gitignore
- devops/ver5/provision.py
- devops/ver5/provision.yaml
- devops/ver5/rabbitmq.advanced.config
- devops/ver5/start_girder.sh
- devops/ver5/start_worker.sh
- dsa5.Dockerfile
This still needs documentation.  There is a Girder 5-based docker compose deployment in the devops/ver5 directory.
The very brief migration notes are:
- You must convert any customizations of the girder or girder worker config files to use environment variables.
- Girder logging will be different (currently, it is in the docker logs, not the info log).
- Although you should be able to switch between a Girder 5 and a Girder 3 base, this is not fully tested.
- If you are adding additional plugins in provisioning, the client build process now uses vite, not Girder build.
For now, the Girder 3 deployment is still the default.
> Girder 5 docker and docker compose

- .circleci/check_updates.sh
- .circleci/config.yml
This explicitly checks the github repos used in the docker build.  If we ever go a long time without updates to any of them, we'd want to do a check any way just to make sure all of the other dependencies and the trivy check still pass.
> Make periodic check only rebuild on changes

- devops/ver5/docker-compose.yml
- devops/ver5/start_dockerlog.py
This switches from memcached to redis, as we want redis for better notifications.
This adds a docker container for persistent logging to a stable location.  This reduces the surprise when switching from girder 3.  Since docker doesn't persist logs across container removal, this does.  Newly added is the ability to persist mongo and rabbitmq logs, allowing a local install to be better debugged if something goes wrong.  Naturally, this wouldn't be used in the minimal configuration or with terraform deployments.
> Improve version 5 docker compose
